spring.datasource.url=jdbc:postgresql://dpg-d6p5psv5gffc738um4q0-a.singapore-postgres.render.com/mediaccess
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=mediaccess_user
spring.datasource.password=pPzuEJKnHncsHZLh8FicerrpJNnq7PTQ
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Config
jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
jwt.expiration=86400000
